In [10]:
import pandas as pd
import numpy as np

x = pd.DataFrame([10,10,np.nan,20,30])
x

0
0  10.0
1  10.0
2   NaN
3  20.0
4  30.0

In [11]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy = 'mean')
x_i = si.fit_transform(x)
x_i

array([[10. ],
       [10. ],
       [17.5],
       [20. ],
       [30. ]])

In [12]:
si = SimpleImputer(strategy = 'most_frequent')
x_i = si.fit_transform(x)
x_i

array([[10.],
       [10.],
       [10.],
       [20.],
       [30.]])

In [13]:
si = SimpleImputer(strategy = 'median')
x_i = si.fit_transform(x)
x_i

array([[10.],
       [10.],
       [15.],
       [20.],
       [30.]])

In [26]:
si = SimpleImputer(strategy = 'constant', fill_value =100)
x_i = si.fit_transform(x)
x_i

array([[ 10.],
       [ 10.],
       [100.],
       [ 20.],
       [ 30.]])

In [28]:
si = SimpleImputer(missing_values=10, strategy = 'constant', fill_value =100)
x_i = si.fit_transform(x_i)
x_i

array([[100.],
       [100.],
       [100.],
       [ 20.],
       [ 30.]])

In [21]:
x_i = x.fillna(0)
x_i

0
0  10.0
1  10.0
2   0.0
3  20.0
4  30.0